local:
  service: Disk
  root: <%= Rails.root.join("storage") %>


#This would be for production, this might not be the final cloud storage choice
amazon:
  service: S3
  access_key_id: ""
  secret_access_key: ""